CREATE TABLE IF NOT EXISTS public.labs
(
    lab_id uuid NOT NULL,
    lab_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    license_number character varying(100) COLLATE pg_catalog."default",
    phone_number character varying(15) COLLATE pg_catalog."default",
    lab_logo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    verification_notes text COLLATE pg_catalog."default",
    verification_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    verified_at timestamp with time zone,
    verified_by_id uuid,
    CONSTRAINT labs_pkey PRIMARY KEY (lab_id),
    CONSTRAINT labs_license_number_key UNIQUE (license_number),
    CONSTRAINT labs_user_id_354de3c5_fk_users_user_id FOREIGN KEY (lab_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT labs_verified_by_id_089b0662_fk_users_user_id FOREIGN KEY (verified_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS public.lab_operating_hours
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    day_of_week integer NOT NULL,
    open_time time without time zone NOT NULL,
    close_time time without time zone NOT NULL,
    is_closed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lab_id uuid NOT NULL,
    CONSTRAINT lab_operating_hours_pkey PRIMARY KEY (id),
    CONSTRAINT lab_operating_hours_lab_id_day_of_week_bc2fe93e_uniq UNIQUE (lab_id, day_of_week),
    CONSTRAINT lab_operating_hours_lab_id_599b71fb_fk_labs_user_id FOREIGN KEY (lab_id)
        REFERENCES public.labs (lab_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT lab_operating_hours_day_of_week_check CHECK (day_of_week >= 0 AND day_of_week <= 6)
);


CREATE TABLE IF NOT EXISTS public.lab_test_categories
(
    category_id   integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    category_name character varying(100) NOT NULL UNIQUE,
    description   text,
    is_active     boolean NOT NULL DEFAULT true,
    created_by    uuid NOT NULL,
    created_at    timestamp with time zone NOT NULL DEFAULT now(),
    updated_by    uuid NOT NULL,
    updated_at    timestamp with time zone NOT NULL DEFAULT now()
);


CREATE TABLE IF NOT EXISTS public.lab_tests
(
    test_id            integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id        integer,
    test_code          character varying(30) NOT NULL UNIQUE, 
    test_name          character varying(255) NOT NULL,
    description        text,
    sample_type        character varying(50) NOT NULL,     -- Blood, Urine, Stool, etc.
    fasting_required   boolean NOT NULL DEFAULT false,
    fasting_hours      integer,                         -- fasting_hours IS NULL OR fasting_hours >= 0
    result_unit        character varying(50),
    normal_range       character varying(100),
    price              numeric(10,2) NOT NULL DEFAULT 0,    -- price >= 0
    turnaround_hours   integer,                         --  turnaround_hours >= 0
    is_active          boolean NOT NULL DEFAULT true,
    created_at         timestamp with time zone NOT NULL DEFAULT now(),
    updated_at         timestamp with time zone NOT NULL DEFAULT now()

    -- CONSTRAINT lab_tests_category_id_fk FOREIGN KEY (category_id)
    --     REFERENCES public.lab_test_categories (category_id)
    --     ON UPDATE NO ACTION
    --     ON DELETE SET NULL,
);

CREATE TABLE IF NOT EXISTS public.lab_test_orders
(
    order_id               uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id             uuid NOT NULL,
    lab_id                 uuid NOT NULL,
    doctor_id              uuid,
    appointment_id         integer,
    order_status           character varying(20) NOT NULL DEFAULT 'PLACED',     -- 'PLACED', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'
    payment_status         character varying(20) NOT NULL DEFAULT 'PENDING',    -- 'PENDING', 'PAID', 'FAILED', 'REFUNDED'
    sample_collection_status character varying(20) NOT NULL DEFAULT 'PENDING',  -- 'PENDING', 'COLLECTED', 'REJECTED'
    total_amount           numeric(10,2) NOT NULL DEFAULT 0,                    -- total_amount >= 0
    notes                  text,
    ordered_at             timestamp with time zone NOT NULL DEFAULT now(),
    updated_at             timestamp with time zone NOT NULL DEFAULT now()

    -- CONSTRAINT lab_test_orders_patient_fk FOREIGN KEY (patient_id)
    --     REFERENCES public.patients (patient_id)
    --     ON UPDATE NO ACTION
    --     ON DELETE RESTRICT,

    -- CONSTRAINT lab_test_orders_lab_fk FOREIGN KEY (lab_id)
    --     REFERENCES public.labs (lab_id)
    --     ON UPDATE NO ACTION
    --     ON DELETE RESTRICT,

    -- CONSTRAINT lab_test_orders_doctor_fk FOREIGN KEY (doctor_id)
    --     REFERENCES public.doctors (doctor_id)
    --     ON UPDATE NO ACTION
    --     ON DELETE SET NULL,

    -- CONSTRAINT lab_test_orders_appointment_fk FOREIGN KEY (appointment_id)
    --     REFERENCES public.doctor_appointments (appointment_id)
    --     ON UPDATE NO ACTION
    --     ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.lab_test_order_items
(
    item_id          integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         uuid NOT NULL,
    test_id          integer NOT NULL,
    price_at_order   numeric(10,2) NOT NULL,                            -- price_at_order >= 0
    discount_amount  numeric(10,2) NOT NULL DEFAULT 0,                  -- discount_amount >= 0
    result_status    character varying(20) NOT NULL DEFAULT 'PENDING',  -- 'PENDING', 'PARTIAL', 'AVAILABLE'
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    updated_at       timestamp with time zone NOT NULL DEFAULT now()

    -- CONSTRAINT lab_test_order_items_pkey PRIMARY KEY (item_id),
    -- CONSTRAINT lab_test_order_items_order_test_key UNIQUE (order_id, test_id),

    -- CONSTRAINT lab_test_order_items_order_fk FOREIGN KEY (order_id)
    --     REFERENCES public.lab_test_orders (order_id)
    --     ON UPDATE NO ACTION
    --     ON DELETE CASCADE,

    -- CONSTRAINT lab_test_order_items_test_fk FOREIGN KEY (test_id)
    --     REFERENCES public.lab_tests (test_id)
    --     ON UPDATE NO ACTION
    --     ON DELETE RESTRICT,
);


CREATE TABLE IF NOT EXISTS public.lab_test_results
(
    result_id        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id          integer NOT NULL UNIQUE,
    result_value     text NOT NULL,
    result_flag      character varying(20),
    result_notes     text,
    report_file      character varying(255),
    reported_by_id   uuid,
    verified_by_id   uuid,
    reported_at      timestamp with time zone NOT NULL DEFAULT now(),
    verified_at      timestamp with time zone,
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    updated_at       timestamp with time zone NOT NULL DEFAULT now()

    -- CONSTRAINT lab_test_results_item_fk FOREIGN KEY (item_id)
    --     REFERENCES public.lab_test_order_items (item_id)
    --     ON UPDATE NO ACTION
    --     ON DELETE CASCADE,

    -- CONSTRAINT lab_test_results_reported_by_fk FOREIGN KEY (reported_by_id)
    --     REFERENCES public.users (user_id)
    --     ON UPDATE NO ACTION
    --     ON DELETE SET NULL,

    -- CONSTRAINT lab_test_results_verified_by_fk FOREIGN KEY (verified_by_id)
    --     REFERENCES public.users (user_id)
    --     ON UPDATE NO ACTION
    --     ON DELETE SET NULL
);