CREATE TABLE IF NOT EXISTS public.addresses
(
    address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    address_line text COLLATE pg_catalog."default" NOT NULL,
    city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    state character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pincode character varying(10) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT addresses_pkey PRIMARY KEY (address_id)
)


CREATE TABLE IF NOT EXISTS public.appointment_slots
(
    slot_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slot_date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    is_booked boolean NOT NULL DEFAULT false,
    is_blocked boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL,
    schedule_id integer NOT NULL,
    CONSTRAINT appointment_slots_pkey PRIMARY KEY (slot_id),
    CONSTRAINT appointment_slots_schedule_id_slot_date_st_c77aed6c_uniq UNIQUE (schedule_id, slot_date, start_time),
    CONSTRAINT appointment_slots_schedule_id_768ac7d2_fk_doctor_sc FOREIGN KEY (schedule_id)
        REFERENCES public.doctor_schedules (schedule_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT appointment_slots_time_check CHECK (start_time < end_time)
)


CREATE TABLE IF NOT EXISTS public.audit_logs
(
    log_id bigint NOT NULL DEFAULT nextval('audit_logs_log_id_seq'::regclass),
    performed_by_id uuid,
    target_user_id uuid,
    action character varying(40) COLLATE pg_catalog."default" NOT NULL,
    entity_type character varying(20) COLLATE pg_catalog."default",
    details text COLLATE pg_catalog."default" NOT NULL,
    status character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'SUCCESS'::character varying,
    ip_address inet,
    user_agent text COLLATE pg_catalog."default",
    duration_ms integer,
    request_path character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT audit_logs_pkey PRIMARY KEY (log_id),
    CONSTRAINT audit_logs_performed_by_id_fkey FOREIGN KEY (performed_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT audit_logs_target_user_id_fkey FOREIGN KEY (target_user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT audit_logs_duration_ms_check CHECK (duration_ms >= 0)
)


CREATE TABLE IF NOT EXISTS public.blood_groups
(
    blood_group_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    blood_group_value character varying(5) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT blood_groups_pkey PRIMARY KEY (blood_group_id),
    CONSTRAINT blood_groups_blood_group_value_key UNIQUE (blood_group_value)
)


CREATE TABLE IF NOT EXISTS public.doctor_appointments
(
    appointment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    appointment_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default",
    cancellation_reason text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    cancelled_by_id uuid,
    doctor_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    slot_id integer,
    CONSTRAINT doctor_appointments_pkey PRIMARY KEY (appointment_id),
    CONSTRAINT doctor_appointments_cancelled_by_id_80395a1b_fk_users_user_id FOREIGN KEY (cancelled_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_appointments_doctor_id_4f36d1d1_fk_doctors_user_id FOREIGN KEY (doctor_id)
        REFERENCES public.doctors (doctor_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_appointments_patient_id_f8f9a694_fk_users_user_id FOREIGN KEY (patient_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_appointments_slot_id_bd041bf6_fk_appointme FOREIGN KEY (slot_id)
        REFERENCES public.appointment_slots (slot_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.doctor_qualifications
(
    doctor_qualification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    institution character varying(255) COLLATE pg_catalog."default",
    year_of_completion integer,
    created_at timestamp with time zone NOT NULL,
    doctor_id uuid NOT NULL,
    qualification_id integer NOT NULL,
    CONSTRAINT doctor_qualifications_pkey PRIMARY KEY (doctor_qualification_id),
    CONSTRAINT doctor_qualifications_doctor_id_qualification_id_562aa436_uniq UNIQUE (doctor_id, qualification_id),
    CONSTRAINT doctor_qualification_qualification_id_10a92a5c_fk_qualifica FOREIGN KEY (qualification_id)
        REFERENCES public.qualifications (qualification_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_qualifications_doctor_id_317a2d59_fk_doctors_user_id FOREIGN KEY (doctor_id)
        REFERENCES public.doctors (doctor_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_qualifications_year_of_completion_check CHECK (year_of_completion >= 0)
);

CREATE TABLE IF NOT EXISTS public.doctor_schedules
(
    schedule_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    consultation_duration_min integer NOT NULL,
    appointment_contact character varying(15) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    doctor_id uuid NOT NULL,
    CONSTRAINT doctor_schedules_pkey PRIMARY KEY (schedule_id),
    CONSTRAINT doctor_schedules_doctor_id_key UNIQUE (doctor_id),
    CONSTRAINT doctor_schedules_doctor_id_44f71506_fk_doctors_user_id FOREIGN KEY (doctor_id)
        REFERENCES public.doctors (doctor_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_schedules_consultation_duration_min_check CHECK (consultation_duration_min >= 0)
);

CREATE TABLE IF NOT EXISTS public.doctor_specializations
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    is_primary boolean NOT NULL,
    years_in_specialty integer,
    created_at timestamp with time zone NOT NULL,
    doctor_id uuid NOT NULL,
    specialization_id integer NOT NULL,
    CONSTRAINT doctor_specializations_pkey PRIMARY KEY (id),
    CONSTRAINT doctor_specializations_doctor_id_specialization_c54b8458_uniq UNIQUE (doctor_id, specialization_id),
    CONSTRAINT doctor_specializatio_specialization_id_fe05463f_fk_specializ FOREIGN KEY (specialization_id)
        REFERENCES public.specializations (specialization_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_specializations_doctor_id_6874ba84_fk_doctors_user_id FOREIGN KEY (doctor_id)
        REFERENCES public.doctors (doctor_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_specializations_years_in_specialty_check CHECK (years_in_specialty >= 0)
);

CREATE TABLE IF NOT EXISTS public.doctor_working_days
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    day_of_week integer NOT NULL,
    arrival time without time zone,
    leaving time without time zone,
    created_at timestamp with time zone NOT NULL,
    schedule_id integer NOT NULL,
    lunch_end time without time zone,
    lunch_start time without time zone,
    CONSTRAINT doctor_working_days_pkey PRIMARY KEY (id),
    CONSTRAINT doctor_working_days_schedule_id_day_of_week_3a07f362_uniq UNIQUE (schedule_id, day_of_week),
    CONSTRAINT doctor_working_days_schedule_id_67dbb916_fk_doctor_sc FOREIGN KEY (schedule_id)
        REFERENCES public.doctor_schedules (schedule_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctor_working_days_arrival_leaving_check CHECK (arrival IS NULL OR leaving IS NULL OR arrival < leaving),
    CONSTRAINT doctor_working_days_day_of_week_check CHECK (day_of_week >= 0 AND day_of_week <= 6)
);

CREATE TABLE IF NOT EXISTS public.doctors
(
    doctor_id uuid NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    experience_years numeric(6,2) NOT NULL,
    phone_number character varying(15) COLLATE pg_catalog."default" NOT NULL,
    consultation_fee numeric(10,2),
    registration_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    profile_image character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    address_id integer,
    gender_id integer,
    verification_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    verification_notes text COLLATE pg_catalog."default",
    verified_at timestamp with time zone,
    verified_by_id uuid,
    CONSTRAINT doctors_pkey PRIMARY KEY (doctor_id),
    CONSTRAINT doctors_address_id_key UNIQUE (address_id),
    CONSTRAINT doctors_address_id_52247b9c_fk_addresses_address_id FOREIGN KEY (address_id)
        REFERENCES public.addresses (address_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctors_gender_id_9b833a22_fk_genders_gender_id FOREIGN KEY (gender_id)
        REFERENCES public.genders (gender_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctors_user_id_480f6e79_fk_users_user_id FOREIGN KEY (doctor_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT doctors_verified_by_id_659a9c03_fk_users_user_id FOREIGN KEY (verified_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.email_verification_table
(
    id bigint NOT NULL DEFAULT nextval('email_verification_table_id_seq'::regclass),
    user_id uuid NOT NULL,
    verification_type_id integer NOT NULL,
    token text COLLATE pg_catalog."default",
    otp character varying(6) COLLATE pg_catalog."default",
    expires_at timestamp with time zone NOT NULL,
    is_used boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT email_verification_table_pkey PRIMARY KEY (id),
    CONSTRAINT email_verification_table_token_key UNIQUE (token),
    CONSTRAINT ev_type_fk FOREIGN KEY (verification_type_id)
        REFERENCES public.verification_types (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT ev_user_fk FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.genders
(
    gender_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    gender_value character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT genders_pkey PRIMARY KEY (gender_id),
    CONSTRAINT genders_gender_value_key UNIQUE (gender_value)
)

CREATE TABLE IF NOT EXISTS public.lab_operating_hours
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    day_of_week integer NOT NULL,
    open_time time without time zone NOT NULL,
    close_time time without time zone NOT NULL,
    is_closed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lab_id uuid NOT NULL,
    CONSTRAINT lab_operating_hours_pkey PRIMARY KEY (id),
    CONSTRAINT lab_operating_hours_lab_id_day_of_week_bc2fe93e_uniq UNIQUE (lab_id, day_of_week),
    CONSTRAINT lab_operating_hours_lab_id_599b71fb_fk_labs_user_id FOREIGN KEY (lab_id)
        REFERENCES public.labs (lab_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT lab_operating_hours_day_of_week_check CHECK (day_of_week >= 0 AND day_of_week <= 6)
);

CREATE TABLE IF NOT EXISTS public.lab_services
(
    service_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    service_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(10,2),
    turnaround_hours integer,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lab_id uuid NOT NULL,
    CONSTRAINT lab_services_pkey PRIMARY KEY (service_id),
    CONSTRAINT lab_services_lab_id_service_name_ec2eeece_uniq UNIQUE (lab_id, service_name),
    CONSTRAINT lab_services_lab_id_747daac2_fk_labs_user_id FOREIGN KEY (lab_id)
        REFERENCES public.labs (lab_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT lab_services_turnaround_hours_check CHECK (turnaround_hours >= 0)
);

CREATE TABLE IF NOT EXISTS public.labs
(
    lab_id uuid NOT NULL,
    lab_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    license_number character varying(100) COLLATE pg_catalog."default",
    phone_number character varying(15) COLLATE pg_catalog."default",
    lab_logo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    address_id integer,
    verification_notes text COLLATE pg_catalog."default",
    verification_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    verified_at timestamp with time zone,
    verified_by_id uuid,
    CONSTRAINT labs_pkey PRIMARY KEY (lab_id),
    CONSTRAINT labs_address_id_key UNIQUE (address_id),
    CONSTRAINT labs_license_number_key UNIQUE (license_number),
    CONSTRAINT labs_address_id_ec0b9bf5_fk_addresses_address_id FOREIGN KEY (address_id)
        REFERENCES public.addresses (address_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT labs_user_id_354de3c5_fk_users_user_id FOREIGN KEY (lab_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT labs_verified_by_id_089b0662_fk_users_user_id FOREIGN KEY (verified_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS public.patients
(
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date,
    mobile character varying(15) COLLATE pg_catalog."default" NOT NULL,
    emergency_contact_name character varying(255) COLLATE pg_catalog."default",
    emergency_contact_phone character varying(15) COLLATE pg_catalog."default",
    profile_image character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    address_id integer,
    blood_group_id integer,
    gender_id integer,
    patient_id uuid NOT NULL,
    CONSTRAINT patients_pkey PRIMARY KEY (patient_id),
    CONSTRAINT patients_address_id_key UNIQUE (address_id),
    CONSTRAINT patients_user_id_key UNIQUE (patient_id),
    CONSTRAINT patients_address_id_309cdd3b_fk_addresses_address_id FOREIGN KEY (address_id)
        REFERENCES public.addresses (address_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT patients_blood_group_id_81adc630_fk_blood_groups_blood_group_id FOREIGN KEY (blood_group_id)
        REFERENCES public.blood_groups (blood_group_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT patients_gender_id_8a67e84f_fk_genders_gender_id FOREIGN KEY (gender_id)
        REFERENCES public.genders (gender_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT patients_user_id_11c42fa7_fk_users_user_id FOREIGN KEY (patient_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);


CREATE TABLE IF NOT EXISTS public.qualifications
(
    qualification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    qualification_code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    qualification_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT qualifications_pkey PRIMARY KEY (qualification_id),
    CONSTRAINT qualifications_qualification_code_key UNIQUE (qualification_code),
    CONSTRAINT qualifications_qualification_name_key UNIQUE (qualification_name)
);


CREATE TABLE IF NOT EXISTS public.specializations
(
    specialization_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    specialization_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT specializations_pkey PRIMARY KEY (specialization_id),
    CONSTRAINT specializations_specialization_name_key UNIQUE (specialization_name)
);

CREATE TABLE IF NOT EXISTS public.user_documents
(
    document_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    document_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    file_path character varying(512) COLLATE pg_catalog."default" NOT NULL,
    original_name character varying(255) COLLATE pg_catalog."default",
    uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
    is_verified boolean NOT NULL,
    verified_at timestamp with time zone,
    user_id uuid NOT NULL,
    verified_by_id uuid,
    CONSTRAINT user_documents_pkey PRIMARY KEY (document_id),
    CONSTRAINT user_documents_user_id_7bfbd08b_fk_users_user_id FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT user_documents_verified_by_id_93da8a66_fk_users_user_id FOREIGN KEY (verified_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)


CREATE TABLE IF NOT EXISTS public.user_roles
(
    role_id integer NOT NULL DEFAULT nextval('user_roles_id_seq'::regclass),
    role character varying(30) COLLATE pg_catalog."default" NOT NULL,
    role_description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_roles_pkey PRIMARY KEY (role_id),
    CONSTRAINT user_roles_name_key UNIQUE (role)
);

CREATE TABLE IF NOT EXISTS public.users
(
    password character varying(128) COLLATE pg_catalog."default",
    user_id uuid NOT NULL DEFAULT gen_random_uuid(),
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    email_verified boolean NOT NULL,
    is_active boolean NOT NULL,
    oauth_provider character varying(100) COLLATE pg_catalog."default",
    oauth_provider_id character varying(255) COLLATE pg_catalog."default",
    two_factor_enabled boolean NOT NULL,
    failed_login_attempts integer NOT NULL,
    lockout_until timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    last_login_at timestamp with time zone,
    role_id integer,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.verification_types
(
    id smallint NOT NULL DEFAULT nextval('verification_types_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT verification_types_pkey PRIMARY KEY (id),
    CONSTRAINT verification_types_name_key UNIQUE (name)
)



CREATE TABLE IF NOT EXISTS public.user_refresh_tokens
(
    token_id    integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id     uuid NOT NULL,
    refresh_token text NOT NULL,
    expires_at  timestamp with time zone NOT NULL,
    is_revoked  boolean NOT NULL DEFAULT false,
    created_at  timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT user_refresh_tokens_pkey PRIMARY KEY (token_id),
    CONSTRAINT user_refresh_tokens_refresh_token_key UNIQUE (refresh_token),

    CONSTRAINT user_refresh_tokens_user_id_fk FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);