CREATE TABLE IF NOT EXISTS public.addresses
(
    address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    address_line text COLLATE pg_catalog."default" NOT NULL,
    city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    state character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pincode character varying(10) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT addresses_pkey PRIMARY KEY (address_id)
)









CREATE TABLE IF NOT EXISTS public.user_documents
(
    document_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    document_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    file_path character varying(512) COLLATE pg_catalog."default" NOT NULL,
    original_name character varying(255) COLLATE pg_catalog."default",
    uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
    is_verified boolean NOT NULL,
    verified_at timestamp with time zone,
    user_id uuid NOT NULL,
    verified_by_id uuid,
    CONSTRAINT user_documents_pkey PRIMARY KEY (document_id),
    CONSTRAINT user_documents_user_id_7bfbd08b_fk_users_user_id FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT user_documents_verified_by_id_93da8a66_fk_users_user_id FOREIGN KEY (verified_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)






CREATE TABLE IF NOT EXISTS public.verification_types
(
    id smallint NOT NULL DEFAULT nextval('verification_types_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT verification_types_pkey PRIMARY KEY (id),
    CONSTRAINT verification_types_name_key UNIQUE (name)
)



