CREATE TABLE IF NOT EXISTS public.labs
(
    lab_id uuid NOT NULL,
    lab_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    license_number character varying(100) COLLATE pg_catalog."default",
    phone_number character varying(15) COLLATE pg_catalog."default",
    lab_logo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    verification_notes text COLLATE pg_catalog."default",
    verification_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    verified_at timestamp with time zone,
    verified_by_id uuid,
    CONSTRAINT labs_pkey PRIMARY KEY (lab_id),
    CONSTRAINT labs_license_number_key UNIQUE (license_number),
    CONSTRAINT labs_user_id_354de3c5_fk_users_user_id FOREIGN KEY (lab_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT labs_verified_by_id_089b0662_fk_users_user_id FOREIGN KEY (verified_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.lab_operating_hours
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    day_of_week integer NOT NULL,
    open_time time without time zone NOT NULL,
    close_time time without time zone NOT NULL,
    max_bookings int not null DEFAULT 10,
    is_closed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lab_id uuid NOT NULL,
    CONSTRAINT lab_operating_hours_pkey PRIMARY KEY (id),
    CONSTRAINT lab_operating_hours_lab_id_day_of_week_bc2fe93e_uniq UNIQUE (lab_id, day_of_week),
    CONSTRAINT lab_operating_hours_lab_id_599b71fb_fk_labs_user_id FOREIGN KEY (lab_id)
        REFERENCES public.labs (lab_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT lab_operating_hours_day_of_week_check CHECK (day_of_week >= 0 AND day_of_week <= 6)
);


create table if not EXISTS public.lab_test_slots
(
    slot_id int not null GENERATED by DEFAULT as identity PRIMARY KEY,
    lab_id uuid not null references public.labs(lab_id) on delete cascade,
    slot_date date not null,
    start_time time not null,
    end_time time not null,
    booked_count int not null DEFAULT 0,
    is_active boolean not null DEFAULT true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);


CREATE TABLE IF NOT EXISTS public.lab_test_categories
(
    category_id   integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    category_name character varying(100) NOT NULL UNIQUE,
    description   text,
    is_active     boolean NOT NULL DEFAULT true,
    created_by    uuid NOT NULL,
    created_at    timestamp with time zone NOT NULL DEFAULT now(),
    updated_by    uuid NOT NULL,
    updated_at    timestamp with time zone NOT NULL DEFAULT now()
);


CREATE TABLE IF NOT EXISTS public.lab_tests
(
    test_id            integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id        integer,
    test_code          character varying(30) NOT NULL UNIQUE, 
    test_name          character varying(255) NOT NULL,
    description        text,
    sample_type        character varying(50) NOT NULL,
    fasting_required   boolean NOT NULL DEFAULT false,
    fasting_hours      integer,
    price              numeric(10,2) NOT NULL DEFAULT 0,
    turnaround_hours    integer,
    is_active          boolean NOT NULL DEFAULT true,
    created_by      uuid,
    updated_by      uuid,
    created_at         timestamp with time zone NOT NULL DEFAULT now(),
    updated_at         timestamp with time zone NOT NULL DEFAULT now()
);


CREATE TABLE test_parameters (
    parameter_id SERIAL PRIMARY KEY,
    test_id INT REFERENCES lab_tests(test_id),
    parameter_name VARCHAR(255),
    unit VARCHAR(50),
    normal_range VARCHAR(100)
);


create table if not exists  public.lab_test_slot_bookings
(
    booking_id uuid not null DEFAULT gen_random_uuid() PRIMARY key,
    patient_id uuid not null REFERENCES public.users (user_id),
    lab_id uuid not null references public.labs(lab_id) on delete cascade,
    slot_id int not null references public.lab_test_slots(slot_id) on delete cascade,
    test_id int not null references public.lab_tests(test_id) on delete cascade,

    collection_type varchar(20) not null,  -- 'lab_visit' | 'home'
    collection_address jsonb,

    booking_status varchar(20) not null default 'BOOKED', -- 'BOOKED', 'COMPLETED', 'CANCELLED'

    subtotal numeric(10,2) not null DEFAULT 0,
    home_collection_charge numeric(10,2) not null DEFAULT 0,
    discount_amount numeric(10,2) not null DEFAULT 0,
    total_amount numeric(10,2) not null DEFAULT 0,

    notes               text,
    cancelled_at        timestamp with time zone,
    cancellation_reason text,
    cancelled_by        uuid, 

    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
)


CREATE TABLE IF NOT EXISTS public.lab_test_reports
(
    result_id        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id    uuid NOT NULL REFERENCES lab_test_slot_bookings(booking_id) ON DELETE CASCADE,
    report_file_url   character varying(255) NOT NULL,
    report_type       character varying(50) DEFAULT 'pdf',
    result_notes     text,
    uploaded_by   uuid,
    uploaded_at       timestamp with time zone NOT NULL DEFAULT now(),
);