CREATE TABLE IF NOT EXISTS public.labs
(
    lab_id uuid NOT NULL,
    lab_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    license_number character varying(100) COLLATE pg_catalog."default",
    phone_number character varying(15) COLLATE pg_catalog."default",
    lab_logo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    verification_notes text COLLATE pg_catalog."default",
    verification_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    verified_at timestamp with time zone,
    verified_by_id uuid,
    CONSTRAINT labs_pkey PRIMARY KEY (lab_id),
    CONSTRAINT labs_license_number_key UNIQUE (license_number),
    CONSTRAINT labs_user_id_354de3c5_fk_users_user_id FOREIGN KEY (lab_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT labs_verified_by_id_089b0662_fk_users_user_id FOREIGN KEY (verified_by_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS public.lab_operating_hours
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    day_of_week integer NOT NULL,
    open_time time without time zone NOT NULL,
    close_time time without time zone NOT NULL,
    is_closed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lab_id uuid NOT NULL,
    CONSTRAINT lab_operating_hours_pkey PRIMARY KEY (id),
    CONSTRAINT lab_operating_hours_lab_id_day_of_week_bc2fe93e_uniq UNIQUE (lab_id, day_of_week),
    CONSTRAINT lab_operating_hours_lab_id_599b71fb_fk_labs_user_id FOREIGN KEY (lab_id)
        REFERENCES public.labs (lab_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT lab_operating_hours_day_of_week_check CHECK (day_of_week >= 0 AND day_of_week <= 6)
);

CREATE TABLE IF NOT EXISTS public.lab_test_categories
(
    category_id   integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    category_name character varying(100) NOT NULL UNIQUE,
    description   text,
    is_active     boolean NOT NULL DEFAULT true,
    created_by    uuid NOT NULL,
    created_at    timestamp with time zone NOT NULL DEFAULT now(),
    updated_by    uuid NOT NULL,
    updated_at    timestamp with time zone NOT NULL DEFAULT now()
);

insert into lab_test_categories (category_name,  description, created_by, updated_by)
values ('Full Body Checkup', 'Comprehensive health screening covering major organs, blood parameters, and overall fitness.', '6994ed8e-d302-4d43-b866-6aa28f353a42',  '6994ed8e-d302-4d43-b866-6aa28f353a42'),
('Heart', 'Cardiac-related tests like cholesterol, ECG, and heart risk markers.', '6994ed8e-d302-4d43-b866-6aa28f353a42', '6994ed8e-d302-4d43-b866-6aa28f353a42'),
('Blood Studies', 'General blood tests to assess hemoglobin, infection, and other conditions.', '6994ed8e-d302-4d43-b866-6aa28f353a42', '6994ed8e-d302-4d43-b866-6aa28f353a42'),
('Vitamin', 'Checks for vitamin deficiencies like Vitamin D, B12, etc.', '6994ed8e-d302-4d43-b866-6aa28f353a42', '6994ed8e-d302-4d43-b866-6aa28f353a42'),
('Thyroid', 'Tests to evaluate thyroid hormone levels (T3, T4, TSH).', '6994ed8e-d302-4d43-b866-6aa28f353a42', '6994ed8e-d302-4d43-b866-6aa28f353a42'),
('Fever', 'Tests to identify causes of fever like infections or viral diseases.', '6994ed8e-d302-4d43-b866-6aa28f353a42', '6994ed8e-d302-4d43-b866-6aa28f353a42'),
('Immunity', 'Tests to assess immune system strength.', '6994ed8e-d302-4d43-b866-6aa28f353a42', '6994ed8e-d302-4d43-b866-6aa28f353a42'),
('Cancer Screening', 'Early detection tests for various types of cancer.', '6994ed8e-d302-4d43-b866-6aa28f353a42', '6994ed8e-d302-4d43-b866-6aa28f353a42');

CREATE TABLE IF NOT EXISTS public.lab_tests
(
    test_id            integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id        integer,
    test_code          character varying(30) NOT NULL UNIQUE, 
    test_name          character varying(255) NOT NULL,
    description        text,
    sample_type        character varying(50) NOT NULL,     -- Blood, Urine, Stool, etc.
    fasting_required   boolean NOT NULL DEFAULT false,
    fasting_hours      integer,                         -- fasting_hours IS NULL OR fasting_hours >= 0
    price              numeric(10,2) NOT NULL DEFAULT 0,    -- price >= 0
    turnaround_hours    integer,                         --  turnaround_hours >= 0
    is_active          boolean NOT NULL DEFAULT true,
    created_by      uuid,
    updated_by      uuid,
    created_at         timestamp with time zone NOT NULL DEFAULT now(),
    updated_at         timestamp with time zone NOT NULL DEFAULT now()

    -- CONSTRAINT lab_tests_category_id_fk FOREIGN KEY (category_id)
    --     REFERENCES public.lab_test_categories (category_id)
    --     ON UPDATE NO ACTION
    --     ON DELETE SET NULL,
);

insert into lab_tests (category_id, test_code, test_name, description, sample_type, fasting_required, price, turnaround_hours )
values (6, 'CBC', 'Complete Blood Count (CBC) Test', 'A CBC Test measures the levels of different blood cells in your body, testing white blood cells, red blood cells, platelets, and haemoglobin and more related parameters. This test gives key insights about various infections, blood disorders and even some cancers. CBC test is done by taking a blood sample from the vein in your arm, fasting is not required for this test.', 'Blood', FALSE, 349, 9);

insert into test_parameters(test_id, parameter_name, unit, normal_range) values
(1, 'Red blood cell (RBC) count', 'X 10 ^ 6 / ul', '4.5 - 5.5' ),
(1, 'Haemoglobin ', 'g/dL', '13.0 - 17.0'),
(1, 'White Blood Cell (WBC) count ', 'X 10 ^ 3 / ul', '4.0 - 10.0'),
(1, 'Mean corpuscular volume (MCV)', 'fl', '83.0 - 110.0'),
(1, 'Mean corpuscular haemoglobin (MCH', 'pq', '27.0 - 32.0');

CREATE TABLE test_parameters (
    parameter_id SERIAL PRIMARY KEY,
    test_id INT REFERENCES lab_tests(test_id),
    parameter_name VARCHAR(255),
    unit VARCHAR(50),
    normal_range VARCHAR(100)
);



CREATE TABLE IF NOT EXISTS public.lab_test_orders
(
    order_id               uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id             uuid NOT NULL,
    lab_id                 uuid NOT NULL,
    doctor_id              uuid,
    appointment_id         integer,
    order_status           character varying(20) NOT NULL DEFAULT 'PLACED',     -- 'PLACED', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'
    payment_status         character varying(20) NOT NULL DEFAULT 'PENDING',    -- 'PENDING', 'PAID', 'FAILED', 'REFUNDED'
    sample_collection_status character varying(20) NOT NULL DEFAULT 'PENDING',  -- 'PENDING', 'COLLECTED', 'REJECTED'
    price_at_order   numeric(10,2) NOT NULL,                            -- price_at_order >= 0
    discount_amount  numeric(10,2) NOT NULL DEFAULT 0,  
    total_amount           numeric(10,2) NOT NULL DEFAULT 0,                    -- total_amount >= 0
    notes                  text,
    ordered_at             timestamp with time zone NOT NULL DEFAULT now(),
    updated_at             timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lab_test_results
(
    result_id        integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    uuid        NOT NULL REFERENCES lab_test_orders(order_id) ON DELETE CASCADE,
    parameter_id integer    NOT NULL REFERENCES test_parameters(parameter_id),
    result_value     text NOT NULL,
    result_flag      character varying(20),
    result_notes     text,
    reported_by_id   uuid,
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    updated_at       timestamp with time zone NOT NULL DEFAULT now()
    CONSTRAINT uq_result_per_order UNIQUE (order_id, parameter_id)
);