# Generated by Django 6.0.1 on 2026-02-13 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=1, null=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')]),
        ),
        migrations.RunSQL("UPDATE patients SET gender = NULL;", reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.gender'),
        ),
    ]

